In [1]:
import glob

import numpy as np
import pandas as pd

pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

path = './data'
csv_files = glob.glob(path + '/*.csv')

df_list = (pd.read_csv(file, usecols=[
    'play_id',
    'old_game_id',
    'week',
    'home_team',
    'away_team',
    'down',
    'play_type',
    'yards_gained',
    'series_success',
    'yrdln',
    'ydstogo',
    'qtr',
    'drive',
    'sp',
    'goal_to_go',
    'time',
    'posteam',
    'defteam',
    'side_of_field',
    'yardline_100',
    'game_date',
    'quarter_seconds_remaining',
    'half_seconds_remaining',
    'game_seconds_remaining',
    'quarter_end',
    'season_type',
    'desc',
    'run_location',
    'run_gap',
    'total_home_score',
    'total_away_score',
    'score_differential',
    'fourth_down_converted',
    ]) for file in csv_files)

df_all = pd.concat(df_list, ignore_index=True)
df_all = df_all[['play_id',
    'old_game_id',
    'week',

    'posteam',
    'defteam',
    'side_of_field',
    

    
    'down',
    'play_type',
    'ydstogo',
    'yards_gained',
    'series_success',
    'yrdln',
    'yardline_100',
    
    'qtr',
    'run_location',
    'run_gap',
    'fourth_down_converted',

    'drive',
    'sp',
    'total_home_score',
    'total_away_score',
    'score_differential',
    
    'goal_to_go',
    'time',
    'home_team',
    'away_team',
    'game_date',
    'quarter_seconds_remaining',
    'half_seconds_remaining',
    'game_seconds_remaining',
    'quarter_end',
    'season_type',
    
    'desc',]]

In [2]:
df_all.describe()

           play_id   old_game_id         week          down       ydstogo  yards_gained  series_success  yardline_100           qtr  fourth_down_converted         drive            sp  total_home_score  total_away_score  score_differential  goal_to_go  quarter_seconds_remaining  half_seconds_remaining  game_seconds_remaining   quarter_end
count  44759.00000  4.475900e+04  44759.00000  37798.000000  44759.000000  43419.000000    44759.000000  41654.000000  44759.000000           43419.000000  44244.000000  44759.000000      44759.000000      44759.000000        42392.000000     44759.0               44754.000000            44754.000000            44754.000000  44759.000000
mean    2190.31263  2.023088e+09      8.95125      2.016800      7.169418      3.922937        0.564535     48.936237      2.561988               0.008890     11.643658      0.072566         11.750352         10.430170           -1.262644         0.0                 410.551861              805.913170             1709.452518      0.017449
std     1272.49150  1.364647e+05      4.99488      1.011408      4.880539      7.727388        0.495823     24.279862      1.128816               0.093868      6.805946      0.259426         10.080839          9.086048           10.555367         0.0                 282.885797              559.570294             1059.000359      0.130939
min        1.00000  2.022122e+09      1.00000      1.000000      0.000000    -24.000000        0.000000      1.000000      1.000000               0.000000      1.000000      0.000000          0.000000          0.000000          -56.000000         0.0                   0.000000                0.000000                0.000000      0.000000
25%     1101.00000  2.023100e+09      4.00000      1.000000      3.000000      0.000000        0.000000     31.000000      2.000000               0.000000      6.000000      0.000000          3.000000          3.000000           -7.000000         0.0                 145.000000              279.000000              785.000000      0.000000
50%     2175.00000  2.023110e+09      9.00000      2.000000      9.000000      0.000000        1.000000     51.000000      2.000000               0.000000     11.000000      0.000000         10.000000          9.000000            0.000000         0.0                 391.000000              790.000000             1800.000000      0.000000
75%     3268.00000  2.023120e+09     13.00000      3.000000     10.000000      6.000000        1.000000     70.000000      4.000000               0.000000     17.000000      0.000000         18.000000         17.000000            4.000000         0.0                 656.000000             1286.000000             2602.000000      0.000000
max     5340.00000  2.023123e+09     17.00000      4.000000     40.000000     92.000000        1.000000     99.000000      5.000000               1.000000     34.000000      1.000000         70.000000         45.000000           55.000000         0.0                 900.000000             1800.000000             3600.000000      1.000000

In [3]:
df_all

       play_id  old_game_id  week posteam defteam side_of_field  down play_type  ydstogo  yards_gained  series_success   yrdln  yardline_100  qtr run_location run_gap  fourth_down_converted  drive  sp  total_home_score  total_away_score  score_differential  goal_to_go   time home_team away_team   game_date  quarter_seconds_remaining  half_seconds_remaining  game_seconds_remaining  quarter_end season_type                                               desc
0            1   2023091007     1     NaN     NaN           NaN   NaN       NaN        0           NaN               1  ARI 35           NaN    1          NaN     NaN                    NaN    NaN   0                 0                 0                 NaN           0  15:00       WAS       ARI  2023-09-10                      900.0                  1800.0                  3600.0            0         REG                                               GAME
1           39   2023091007     1     WAS     ARI           ARI   NaN   kickoff        0           0.0               1  ARI 35          35.0    1          NaN     NaN                    0.0    1.0   0                 0                 0                 0.0           0  15:00       WAS       ARI  2023-09-10                      900.0                  1800.0                  3600.0            0         REG  5-M.Prater kicks 65 yards from ARI 35 to end z...
2           55   2023091007     1     WAS     ARI           WAS   1.0       run       10           3.0               1  WAS 25          75.0    1        right  tackle                    0.0    1.0   0                 0                 0                 0.0           0  15:00       WAS       ARI  2023-09-10                      900.0                  1800.0                  3600.0            0         REG  (15:00) (Shotgun) 8-B.Robinson right tackle to...
3           77   2023091007     1     WAS     ARI           WAS   2.0      pass        7           6.0               1  WAS 28          72.0    1          NaN     NaN                    0.0    1.0   0                 0                 0                 0.0           0  14:30       WAS       ARI  2023-09-10                      870.0                  1770.0                  3570.0            0         REG  (14:30) (Shotgun) 14-S.Howell pass short right...
4          102   2023091007     1     WAS     ARI           WAS   3.0       run        1           2.0               1  WAS 34          66.0    1         left   guard                    0.0    1.0   0                 0                 0                 0.0           0  13:55       WAS       ARI  2023-09-10                      835.0                  1735.0                  3535.0            0         REG  (13:55) 23-C.Rodriguez left guard to WAS 36 fo...
...        ...          ...   ...     ...     ...           ...   ...       ...      ...           ...             ...     ...           ...  ...          ...     ...                    ...    ...  ..               ...               ...                 ...         ...    ...       ...       ...         ...                        ...                     ...                     ...          ...         ...                                                ...
44754     3442   2023123103    17     HOU     TEN           HOU   4.0      punt        5           0.0               0  HOU 15          85.0    4          NaN     NaN                    0.0   17.0   0                26                 3                23.0           0  02:00       HOU       TEN  2023-12-31                      120.0                   120.0                   120.0            0         REG  (2:00) 11-C.Johnston punts 52 yards to TEN 33,...
44755     3475   2023123103    17     TEN     HOU           TEN   1.0       run       10           3.0               1  TEN 42          58.0    4         left     end                    0.0   18.0   0                26                 3               -23.0           0  01:50       HOU       TEN  2023-12-31                      110.0                   110.0                   110.0            0         REG  (1:50) 61-J.Ojukwu reported in as eligible.  2...
44756     3506   2023123103    17     TEN     HOU           TEN   2.0       run        7           8.0               1  TEN 45          55.0    4        right   guard                    0.0   18.0   0                26                 3               -23.0           0  01:05       HOU       TEN  2023-12-31                       65.0                    65.0                    65.0            0         REG  (1:05) 61-J.Ojukwu reported in as eligible.  2...
44757     3530   2023123103    17     TEN     HOU           HOU   1.0       run       10           0.0               0  HOU 47          47.0    4        right  tackle                    0.0   18.0   0                26                 3               -23.0           0  00:21       HOU       TEN  2023-12-31                       21.0                    21.0                    21.0            0         REG  (:21) 61-J.Ojukwu reported in as eligible.  20...
44758     3554   2023123103    17     TEN     HOU           NaN   NaN       NaN        0           NaN               0     NaN           NaN    4          NaN     NaN                    NaN   18.0   0                26                 3               -23.0           0  00:00       HOU       TEN  2023-12-31                        0.0                     0.0                     0.0            0         REG                                           END GAME

[44759 rows x 33 columns]

In [4]:
fourth_down_all = df_all.loc[df_all['down'] == 4]
fourth_down_all

       play_id  old_game_id  week posteam defteam side_of_field  down   play_type  ydstogo  yards_gained  series_success   yrdln  yardline_100  qtr run_location run_gap  fourth_down_converted  drive  sp  total_home_score  total_away_score  score_differential  goal_to_go   time home_team away_team   game_date  quarter_seconds_remaining  half_seconds_remaining  game_seconds_remaining  quarter_end season_type                                               desc
10         245   2023091007     1     WAS     ARI           ARI   4.0        punt        7           0.0               0  ARI 49          49.0    1          NaN     NaN                    0.0    1.0   0                 0                 0                 0.0           0  11:08       WAS       ARI  2023-09-10                      668.0                  1568.0                  3368.0            0         REG  (11:08) 5-T.Way punts 42 yards to ARI 7, Cente...
17         427   2023091007     1     ARI     WAS           ARI   4.0        punt        8           0.0               0  ARI 30          70.0    1          NaN     NaN                    0.0    2.0   0                 0                 0                 0.0           0  07:45       WAS       ARI  2023-09-10                      465.0                  1365.0                  3165.0            0         REG  (7:45) 16-N.Cooney punts 51 yards to WAS 19, C...
36         958   2023091007     1     ARI     WAS           WAS   4.0  field_goal        9           0.0               0  WAS 11          11.0    1          NaN     NaN                    0.0    4.0   1                 7                 3                -7.0           0  00:56       WAS       ARI  2023-09-10                       56.0                   956.0                  2756.0            0         REG  (:56) 5-M.Prater 28 yard field goal is GOOD, C...
46        1237   2023091007     1     ARI     WAS           WAS   4.0  field_goal        9           0.0               0  WAS 36          36.0    2          NaN     NaN                    0.0    6.0   1                 7                 6                -4.0           0  13:31       WAS       ARI  2023-09-10                      811.0                   811.0                  2611.0            0         REG  (13:31) 5-M.Prater 54 yard field goal is GOOD,...
60        1601   2023091007     1     ARI     WAS           ARI   4.0        punt       11           0.0               0  ARI 15          85.0    2          NaN     NaN                    0.0    8.0   0                 7                 6                -1.0           0  06:24       WAS       ARI  2023-09-10                      384.0                   384.0                  2184.0            0         REG  (6:24) 16-N.Cooney punts 34 yards to ARI 49, C...
...        ...          ...   ...     ...     ...           ...   ...         ...      ...           ...             ...     ...           ...  ...          ...     ...                    ...    ...  ..               ...               ...                 ...         ...    ...       ...       ...         ...                        ...                     ...                     ...          ...         ...                                                ...
44735     3003   2023123103    17     HOU     TEN           HOU   4.0        punt       14           0.0               0  HOU 41          59.0    4          NaN     NaN                    0.0   13.0   0                23                 3                20.0           0  10:27       HOU       TEN  2023-12-31                      627.0                   627.0                   627.0            0         REG  (10:27) 11-C.Johnston punts 49 yards to TEN 10...
44741     3146   2023123103    17     TEN     HOU           TEN   4.0        pass        1          -7.0               0  TEN 42          58.0    4          NaN     NaN                    0.0   14.0   0                23                 3               -20.0           0  07:40       HOU       TEN  2023-12-31                      460.0                   460.0                   460.0            0         REG  (7:40) (Shotgun) 17-R.Tannehill sacked at TEN ...
44745     3232   2023123103    17     HOU     TEN           TEN   4.0  field_goal        8           0.0               0  TEN 33          33.0    4          NaN     NaN                    0.0   15.0   1                26                 3                20.0           0  05:37       HOU       TEN  2023-12-31                      337.0                   337.0                   337.0            0         REG  (5:37) 15-K.Fairbairn 51 yard field goal is GO...
44750     3345   2023123103    17     TEN     HOU           TEN   4.0        punt        9           0.0               0  TEN 26          74.0    4          NaN     NaN                    0.0   16.0   0                26                 3               -23.0           0  04:05       HOU       TEN  2023-12-31                      245.0                   245.0                   245.0            0         REG  (4:05) 13-T.Zentner punts 64 yards to HOU 10, ...
44754     3442   2023123103    17     HOU     TEN           HOU   4.0        punt        5           0.0               0  HOU 15          85.0    4          NaN     NaN                    0.0   17.0   0                26                 3                23.0           0  02:00       HOU       TEN  2023-12-31                      120.0                   120.0                   120.0            0         REG  (2:00) 11-C.Johnston punts 52 yards to TEN 33,...

[4066 rows x 33 columns]

In [5]:
fourth_down_all['play_type'].value_counts()

punt          2124
field_goal     943
pass           473
run            275
no_play        237
qb_kneel         6
Name: play_type, dtype: int64

In [6]:
fourth_down_run_all = fourth_down_all.loc[fourth_down_all['play_type'] == 'run']
fourth_down_run_all

       play_id  old_game_id  week posteam defteam side_of_field  down play_type  ydstogo  yards_gained  series_success   yrdln  yardline_100  qtr run_location run_gap  fourth_down_converted  drive  sp  total_home_score  total_away_score  score_differential  goal_to_go   time home_team away_team   game_date  quarter_seconds_remaining  half_seconds_remaining  game_seconds_remaining  quarter_end season_type                                               desc
311       3413   2023091100     1     NYJ     BUF           BUF   4.0       run        1           2.0               1  BUF 18          18.0    4       middle     NaN                    1.0   19.0   0                13                13                 0.0           0  02:50       NYJ       BUF  2023-09-11                      170.0                   170.0                   170.0            0         REG  (2:50) 2-Z.Wilson up the middle to BUF 16 for ...
358        403   2023091000     1     CAR     ATL           ATL   4.0       run        1          -1.0               0  ATL 11          11.0    1         left  tackle                    0.0    2.0   0                 0                 0                 0.0           0  06:14       ATL       CAR  2023-09-10                      374.0                  1274.0                  3074.0            0         REG  (6:14) (Shotgun) 30-C.Hubbard left tackle to A...
508       4282   2023091000     1     CAR     ATL           ATL   4.0       run       15           4.0               0  ATL 34          34.0    4        right  tackle                    0.0   24.0   0                24                10               -14.0           0  00:22       ATL       CAR  2023-09-10                       22.0                    22.0                    22.0            0         REG  (:22) (Shotgun) 9-B.Young scrambles right tack...
807       2957   2023091013     1     NYG     DAL           NYG   4.0       run        1           1.0               1  NYG 47          53.0    3       middle     NaN                    1.0   15.0   0                 0                33               -33.0           0  01:15       NYG       DAL  2023-09-10                       75.0                   975.0                   975.0            0         REG  (1:15) 8-D.Jones up the middle to NYG 48 for 1...
866        386   2023090700     1     DET      KC           DET   4.0       run        2           3.0               1  DET 17          83.0    1       middle     NaN                    1.0    3.0   0                 0                 0                 0.0           0  09:27        KC       DET  2023-09-07                      567.0                  1467.0                  3267.0            0         REG  (9:27) (Punt formation) Direct snap to 42-J.Re...
...        ...          ...   ...     ...     ...           ...   ...       ...      ...           ...             ...     ...           ...  ...          ...     ...                    ...    ...  ..               ...               ...                 ...         ...    ...       ...       ...         ...                        ...                     ...                     ...          ...         ...                                                ...
43775     4145   2023123100    17     MIA     BAL           MIA   4.0       run        5           3.0               0  MIA 30          70.0    4         left   guard                    0.0   24.0   0                56                19               -37.0           0  00:18       BAL       MIA  2023-12-31                       18.0                    18.0                    18.0            0         REG  (:18) (Shotgun) 35-C.Brooks left guard to MIA ...
44272     4147   2023122800    17     NYJ     CLE           NYJ   4.0       run        6           5.0               0  NYJ 27          73.0    4         left     end                    0.0   23.0   0                34                20               -14.0           0  05:37       CLE       NYJ  2023-12-28                      337.0                   337.0                   337.0            0         REG  (5:37) (No Huddle, Shotgun) 14-T.Siemian scram...
44318      555   2023123110    17     PIT     SEA           SEA   4.0       run        1           1.0               1  SEA 45          45.0    1         left   guard                    1.0    3.0   0                 0                 0                 0.0           0  06:23       SEA       PIT  2023-12-31                      383.0                  1283.0                  3083.0            0         REG  (6:23) 2-M.Rudolph left guard to SEA 44 for 1 ...
44426     3163   2023123110    17     PIT     SEA           SEA   4.0       run        1           2.0               1  SEA 13          13.0    4         left   guard                    1.0   15.0   0                20                24                 4.0           0  09:49       SEA       PIT  2023-12-31                      589.0                   589.0                   589.0            0         REG  (9:49) 2-M.Rudolph left guard to SEA 11 for 2 ...
44593     3192   2023123109    17      SF     WAS           WAS   4.0       run        1          -1.0               0   WAS 1           1.0    4         left     end                    0.0   14.0   0                10                27                17.0           0  04:01       WAS        SF  2023-12-31                      241.0                   241.0                   241.0            0         REG  (4:01) 25-E.Mitchell left end to WAS 2 for -1 ...

[275 rows x 33 columns]

In [7]:
fourth_down_run_all['ydstogo'].value_counts()

1     205
2      33
3       9
4       7
5       5
7       5
13      3
6       2
18      2
15      1
8       1
16      1
10      1
Name: ydstogo, dtype: int64

In [8]:
fourth_down_run_convert_all = fourth_down_run_all[fourth_down_run_all['fourth_down_converted'] == 1]
fourth_down_run_convert_all

       play_id  old_game_id  week posteam defteam side_of_field  down play_type  ydstogo  yards_gained  series_success   yrdln  yardline_100  qtr run_location run_gap  fourth_down_converted  drive  sp  total_home_score  total_away_score  score_differential  goal_to_go   time home_team away_team   game_date  quarter_seconds_remaining  half_seconds_remaining  game_seconds_remaining  quarter_end season_type                                               desc
311       3413   2023091100     1     NYJ     BUF           BUF   4.0       run        1           2.0               1  BUF 18          18.0    4       middle     NaN                    1.0   19.0   0                13                13                 0.0           0  02:50       NYJ       BUF  2023-09-11                      170.0                   170.0                   170.0            0         REG  (2:50) 2-Z.Wilson up the middle to BUF 16 for ...
807       2957   2023091013     1     NYG     DAL           NYG   4.0       run        1           1.0               1  NYG 47          53.0    3       middle     NaN                    1.0   15.0   0                 0                33               -33.0           0  01:15       NYG       DAL  2023-09-10                       75.0                   975.0                   975.0            0         REG  (1:15) 8-D.Jones up the middle to NYG 48 for 1...
866        386   2023090700     1     DET      KC           DET   4.0       run        2           3.0               1  DET 17          83.0    1       middle     NaN                    1.0    3.0   0                 0                 0                 0.0           0  09:27        KC       DET  2023-09-07                      567.0                  1467.0                  3267.0            0         REG  (9:27) (Punt formation) Direct snap to 42-J.Re...
1566      4441   2023091003     1     IND     JAX           JAX   4.0       run        5           5.0               1   JAX 8           8.0    4        right   guard                    1.0   28.0   0                21                31               -10.0           0  01:28       IND       JAX  2023-09-10                       88.0                    88.0                    88.0            0         REG  (1:28) (No Huddle, Shotgun) 5-A.Richardson scr...
1712      3321   2023091012     1      LA     SEA           SEA   4.0       run        1           1.0               1   SEA 1           1.0    4         left     end                    1.0   13.0   1                13                23                 4.0           0  09:49       SEA        LA  2023-09-10                      589.0                   589.0                   589.0            0         REG   (9:49) 3-C.Akers left end for 1 yard, TOUCHDOWN.
...        ...          ...   ...     ...     ...           ...   ...       ...      ...           ...             ...     ...           ...  ...          ...     ...                    ...    ...  ..               ...               ...                 ...         ...    ...       ...       ...         ...                        ...                     ...                     ...          ...         ...                                                ...
42697     3324   2023123112    17      KC     CIN           CIN   4.0       run        1           2.0               1  CIN 36          36.0    4        right     end                    1.0   16.0   0                19                17                 2.0           0  09:09        KC       CIN  2023-12-31                      549.0                   549.0                   549.0            0         REG  (9:09) 15-P.Mahomes scrambles right end to CIN...
43189     2914   2023123111    17     DEN     LAC           DEN   4.0       run        1           1.0               1  DEN 34          66.0    3         left   guard                    1.0   15.0   0                13                 6                 7.0           0  04:26       DEN       LAC  2023-12-31                      266.0                  1166.0                  1166.0            0         REG  (4:26) 75-Q.Bailey reported in as eligible.  3...
43370     3070   2023123106    17     NYG      LA            LA   4.0       run        1           2.0               1   LA 25          25.0    3         left   guard                    1.0   19.0   0                16                20                -4.0           0  00:43       NYG        LA  2023-12-31                       43.0                   943.0                   943.0            0         REG  (:43) (Shotgun) 26-S.Barkley left guard to LA ...
44318      555   2023123110    17     PIT     SEA           SEA   4.0       run        1           1.0               1  SEA 45          45.0    1         left   guard                    1.0    3.0   0                 0                 0                 0.0           0  06:23       SEA       PIT  2023-12-31                      383.0                  1283.0                  3083.0            0         REG  (6:23) 2-M.Rudolph left guard to SEA 44 for 1 ...
44426     3163   2023123110    17     PIT     SEA           SEA   4.0       run        1           2.0               1  SEA 13          13.0    4         left   guard                    1.0   15.0   0                20                24                 4.0           0  09:49       SEA       PIT  2023-12-31                      589.0                   589.0                   589.0            0         REG  (9:49) 2-M.Rudolph left guard to SEA 11 for 2 ...

[193 rows x 33 columns]

In [9]:
fourth_down_run_convert_all['ydstogo'].value_counts()

1    154
2     20
3      7
5      4
4      4
7      3
8      1
Name: ydstogo, dtype: int64

In [10]:
fourth_down_run_convert_all['posteam'].value_counts()

PHI    12
CLE     9
NYG     9
DEN     9
CAR     9
NYJ     8
DET     8
PIT     7
JAX     7
MIN     7
ARI     7
CHI     7
TB      7
TEN     6
NO      6
DAL     6
LV      6
BAL     6
ATL     5
MIA     5
KC      5
CIN     4
HOU     4
BUF     4
WAS     4
LAC     4
SEA     4
LA      4
IND     4
NE      4
GB      3
SF      3
Name: posteam, dtype: int64

In [12]:
PHI_all = df_all.loc[df_all['posteam'] == 'PHI']
PHI_less_than_2yds_run = PHI_all.loc[(PHI_all['ydstogo'] <= 2) & (PHI_all['play_type'] == 'run')]
PHI_less_than_2yds_run

       play_id  old_game_id  week posteam defteam side_of_field  down play_type  ydstogo  yards_gained  series_success   yrdln  yardline_100  qtr run_location run_gap  fourth_down_converted  drive  sp  total_home_score  total_away_score  score_differential  goal_to_go   time home_team away_team   game_date  quarter_seconds_remaining  half_seconds_remaining  game_seconds_remaining  quarter_end season_type                                               desc
2108       165   2023091011     1     PHI      NE            NE   2.0       run        2           1.0               1   NE 40          40.0    1        right  tackle                    0.0    1.0   0                 0                 0                 0.0           0  12:31        NE       PHI  2023-09-10                      751.0                  1651.0                  3451.0            0         REG  (12:31) (Shotgun) 14-K.Gainwell right tackle t...
2109       187   2023091011     1     PHI      NE            NE   3.0       run        1           5.0               1   NE 39          39.0    1       middle     NaN                    0.0    1.0   0                 0                 0                 0.0           0  12:04        NE       PHI  2023-09-10                      724.0                  1624.0                  3424.0            0         REG  (12:04) (No Huddle, Shotgun) 14-K.Gainwell up ...
2111       246   2023091011     1     PHI      NE            NE   2.0       run        2           4.0               1   NE 26          26.0    1         left   guard                    0.0    1.0   0                 0                 0                 0.0           0  11:29        NE       PHI  2023-09-10                      689.0                  1589.0                  3389.0            0         REG  (11:29) (No Huddle, Shotgun) 14-K.Gainwell lef...
4438      1326   2023091400     2     PHI     MIN           MIN   3.0       run        1           4.0               1  MIN 45          45.0    2        right   guard                    0.0    8.0   0                 3                 7                -4.0           0  06:51       PHI       MIN  2023-09-14                      411.0                   411.0                  2211.0            0         REG  (6:51) (No Huddle, Shotgun) 35-B.Scott right g...
4440      1375   2023091400     2     PHI     MIN           MIN   2.0       run        2           5.0               1  MIN 33          33.0    2       middle     NaN                    0.0    8.0   0                 3                 7                -4.0           0  05:47       PHI       MIN  2023-09-14                      347.0                   347.0                  2147.0            0         REG  (5:47) (Shotgun) 35-B.Scott up the middle to M...
...        ...          ...   ...     ...     ...           ...   ...       ...      ...           ...             ...     ...           ...  ...          ...     ...                    ...    ...  ..               ...               ...                 ...         ...    ...       ...       ...         ...                        ...                     ...                     ...          ...         ...                                                ...
41622     2951   2023122501    16     PHI     NYG           PHI   3.0       run        1           3.0               1  PHI 25          75.0    3       middle     NaN                    0.0   15.0   0                20                10                10.0           0  05:11       PHI       NYG  2023-12-25                      311.0                  1211.0                  1211.0            0         REG  (5:11) (No Huddle) 1-J.Hurts up the middle to ...
42178     2720   2023123107    17     PHI     ARI           PHI   2.0       run        1           4.0               1  PHI 34          66.0    3        right  tackle                    0.0   11.0   0                21                21                 0.0           0  01:35       PHI       ARI  2023-12-31                       95.0                   995.0                   995.0            0         REG  (1:35) (No Huddle, Shotgun) 0-D.Swift right ta...
42186     2897   2023123107    17     PHI     ARI           ARI   3.0       run        1           0.0               1  ARI 16          16.0    4       middle     NaN                    0.0   11.0   0                21                21                 0.0           0  12:57       PHI       ARI  2023-12-31                      777.0                   777.0                   777.0            0         REG  (12:57) (No Huddle) 1-J.Hurts up the middle to...
42187     2919   2023123107    17     PHI     ARI           ARI   4.0       run        1           1.0               1  ARI 16          16.0    4         left   guard                    1.0   11.0   0                21                21                 0.0           0  12:20       PHI       ARI  2023-12-31                      740.0                   740.0                   740.0            0         REG  (12:20) 1-J.Hurts left guard to ARI 15 for 1 y...
42189     2963   2023123107    17     PHI     ARI           ARI   2.0       run        2          -7.0               1   ARI 7           7.0    4         left     end                    0.0   11.0   0                21                21                 0.0           0  10:49       PHI       ARI  2023-12-31                      649.0                   649.0                   649.0            0         REG  (10:49) (Shotgun) 1-J.Hurts left end to ARI 14...

[72 rows x 33 columns]

In [13]:
PHI_less_than_2yds_run['series_success'].value_counts()

1    66
0     6
Name: series_success, dtype: int64